### ISSUE TITLE
Set USD/ETC rate to something meaningful

### ISSUE THREAD

**Issue by q9f** [openetc/openetc#4]
ref 4c5b149

**Comment by antsankov** [comment]
I am looking at this [line in particular](https://github.com/openetc/openetc/commit/4c5b14903969c7252b41ed521e5ca4f32d434b94#diff-54d6bbd5addb7a0d39c647e4e33e6990R740) for getting the USD Price of ETC:

`  + ARG arg_usd_per_eth: (String) = "0", or |c: &Config| c.mining.as_ref()?.usd_per_eth.clone()` 

I can either hardcode it to something like "5" or "10", or if it requires changing of endpoints to an ETC Oracle service as well. Does one approach make more sense?
